---
abstract: 'Debug and inspect your template variables for Dancer'
author:
  - 'Thomas Müller <tmueller@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-Dancer-TemplateVariables
requires:
  Dancer: 0
  Data::Dumper: 0
  Plack::Middleware::Debug::Base: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.001
